### ISSUE TITLE
lrn("clust.ap") not working when apclust is not installed 

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3cluster#18]
See https://github.com/mlr-org/mlr3/issues/732

**Comment by mllg** [comment]
We need to avoid declaring hyperparameters which require the package to be loaded. In this specific case, I would suggest to just remove the default value and document it instead. Alternatively, use a `p_uty()` if this is possible here.

**Comment by damirpolat** [comment]
#41 is the same issue and it's been resolved
