### ISSUE TITLE
library error

### ISSUE THREAD

**Issue by xhxlilium** [mlr-org/mlr3cluster#24]
I install the mlr3cluster through install.packages("mlr3cluster ") without error. However, the error occurs when I library it

`Error: package or namespace load failed for ‘mlr3cluster’:
 .onLoad failed in loadNamespace() for 'mlr3cluster', details:
  call: rbindlist(l, use.names, fill, idcol)
  error: Item 2 has 6 columns, inconsistent with item 1 which has 7 columns. To fill missing columns use fill=TRUE.`

I have tried to remove it and install  again but of no use. Again, I tried to install for the source of github, and still does not work, and another error raise:
`Error: package or namespace load failed for ‘mlr3cluster’ in get(Info[i, 1], envir = env):
 lazy-load database 'D:/R-4.1.0/library/mlr3cluster/R/mlr3cluster.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1`
How could I fix it?

**Comment by damirpolat** [comment]
Are you trying to install the package on Windows?

**Comment by xhxlilium** [comment]
yes，Win10



---Original---
From: "Damir ***@***.***&gt;
Date: Sun, Aug 14, 2022 07:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mlr-org/mlr3cluster] library error (Issue #24)




 
Are you trying to install the package on Windows?

**Comment by damirpolat** [comment]
I just submitted a new version (0.1.4) to CRAN. Let me know if still doesn't work after that.

**Comment by xhxlilium** [comment]
It works well now, thanks very much!
