### ISSUE TITLE
[Feature request] Add Gaussian Mixture Models (Hard and fuzzy clustering)

### ISSUE THREAD

**Issue by mmeierer** [mlr-org/mlr3cluster#26]
Consider adding Gaussian Mixture Models (GMM) with the option do do both hard and fuzzy clustering. See e.g., https://brilliant.org/wiki/gaussian-mixture-model/.

An alternative implementation is e.g. available in the clusteR package (https://cran.r-project.org/web/packages/ClusterR/vignettes/the_clusterR_package.html).

Having this algorithm in mlr3cluster would complete the set of fundamental clustering algorithm and thus, the need to rely on the routine of another package when applying GMM.

**Comment by damirpolat** [comment]
I'll take a look!

**Comment by damirpolat** [comment]
Hey @mmeierer, I added 'Mclust' from 'mclust' package in main branch. Let me know if there's anything else!

**Comment by damirpolat** [comment]
Version 0.1.5 includes mclust learner. Closing this for now.
