### ISSUE TITLE
Affinity Propagation cannot be constructed without having the package installed

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3cluster#41]
https://github.com/mlr-org/mlr3cluster/blob/161aee5e75aa299bea29617020339768a8d9a75c/R/LearnerClustAffinityPropagation.R#L30-L47

Learners should be constructable without having their packages installed. 
This is important, because otherwise the mlr_learners -> Dictionary conversion fails, when someone does not have the `apcluster` package installed.

**Comment by damirpolat** [comment]
I unset `s` param so users need to set it manually now. This should fix the issue, thanks!
